DROP PROCEDURE IF EXISTS PR_IS_VALID_SEAT;
DELIMITER !
CREATE PROCEDURE PR_IS_VALID_SEAT(SEATNUMBER INT, OUT ERROR BOOLEAN, OUT COMMENTS VARCHAR(200))
BEGIN
	SET ERROR = TRUE;
	IF NOT EXISTS(SELECT ID FROM SEAT WHERE ID = SEATNUMBER)
	THEN
		SET COMMENTS = "THE SEAT YOU HAVE CHOSEN IS IN THE BERMUDA TRIANGLE PROBABLY WE WILL FIND IT ONE DAY ITS NOT TODAY";
	ELSEIF (SELECT STATUSID FROM SEAT WHERE ID = SEATNUMBER) = 2 -- SEAT TAKEN
	THEN
		SET COMMENTS = "THE CHOSEN SEAT HAS ALREADY BEEN TAKEN YOU COULD WAIT FOR IT OR ASK FOR ANOTHER ONE";
	ELSE
		SET ERROR = FALSE;
	END IF;
END !

/*CALL PR_IS_VALID_SEAT(-1, @ERR, @CMMT);
SELECT @ERR, @CMMT;*/