DROP PROCEDURE IF EXISTS PR_SUBORDER_SPLITTER;
DELIMITER !
CREATE PROCEDURE PR_SUBORDER_SPLITTER(ORDERS VARCHAR(200), SEATNO INT)
BEGIN
DECLARE SUBORDER VARCHAR(50);
SET SUBORDER = SUBSTRING_INDEX(ORDERS,',',1);
WHILE (SUBORDER <> ORDERS)
DO
	SET SUBORDER = SUBSTRING_INDEX(ORDERS,',',1);
	SET ORDERS = REPLACE(ORDERS,CONCAT(SUBORDER,','),'');
	/*IF POSITION(' ' IN SUBORDER) = 1
	THEN
		SET SUBORDER = 
	END IF;*/
	CALL PR_NAME_QTY_DIVIDER (SUBORDER, SEATNO);
END WHILE;
CALL ORDERSPROCEDURE(SEATNO);
END !
DELIMITER ;

/*CALL PR_SUBORDER_SPLITTER('IDLY 10,DOSA 3,POORI 12',4);*/

DROP PROCEDURE IF EXISTS PR_NAME_QTY_DIVIDER;
DELIMITER !
CREATE PROCEDURE PR_NAME_QTY_DIVIDER(SUBORDER VARCHAR(50), SEATNUMBER INT)
BEGIN
DECLARE FOODNAME VARCHAR(20);
DECLARE CHAR_QTY VARCHAR(10);
DECLARE QTY INT;
DECLARE FEILD VARCHAR(20);
DECLARE ERROR BOOLEAN;
SET FOODNAME = '';
SET QTY = 0;
SET FEILD = SUBSTRING_INDEX(SUBORDER,' ',1);
SET ERROR = FALSE;

WHILELOOP: WHILE (SUBORDER <> FEILD)
DO
	SET FEILD = SUBSTRING_INDEX(SUBORDER,' ',1);
	SET SUBORDER = REPLACE(SUBORDER,CONCAT(FEILD,' '),'');
	-- SELECT FEILD;
	IF FEILD <> '0'
	THEN
		IF (CONVERT(FEILD, SIGNED) <> 0)
		THEN
			SET QTY = CONVERT(FEILD, SIGNED);
			IF QTY <= 0
			THEN
				SET ERROR = TRUE;
				LEAVE WHILELOOP;
			END IF; 
		ELSE
			SET FOODNAME = CONCAT(FOODNAME,' ',FEILD);
		END IF;
	ELSE
		SET ERROR = TRUE;
		LEAVE WHILELOOP;
	END IF;
END WHILE;
SET FOODNAME = UPPER(TRIM(FOODNAME));
INSERT INTO INPUTORDERS (FOOD, QTY, SEATID) VALUES (FOODNAME, QTY, SEATNUMBER);
-- SELECT SUBORDER,FEILD,FOODNAME,QTY,ERROR;

END !
DELIMITER ;

-- CALL PR_NAME_QTY_DIVIDER('FRIED RICE 3', 5);

SELECT CONVERT('IDLU', SIGNED);
