DROP FUNCTION IF EXISTS SEATALLOCATER;
DELIMITER !
CREATE FUNCTION SEATALLOCATER()
RETURNS INT
BEGIN
DECLARE SEATNUMBER TINYINT;
DECLARE TOTALSEATS TINYINT;
DECLARE FLAG BOOLEAN;
SET TOTALSEATS = (SELECT COUNT(*) FROM SEAT);
SET SEATNUMBER = (FLOOR(RAND()*(TOTALSEATS-1+1))+1);
SET @I = 1;
SET FLAG = FALSE;
SEATLOOP: WHILE ((SELECT ID FROM SEAT WHERE STATUSID = 1 ORDER BY STATUSID LIMIT 1) IS NOT NULL) -- IF SEAT IS AVAILABLE 1 SO UNTIL ITS AVAILABLE
DO
	SET SEATNUMBER = FLOOR(RAND()*(TOTALSEATS-1+1))+1;
	IF (SELECT STATUSID FROM SEAT WHERE ID = SEATNUMBER) = 1
	THEN
		LEAVE SEATLOOP;
	END IF;
END WHILE;
IF((SELECT ID FROM SEAT WHERE STATUSID = 1 ORDER BY STATUSID LIMIT 1))
THEN
	RETURN SEATNUMBER;
ELSE
	RETURN 0;
END IF;
END !
DELIMITER ;

/*SELECT SEATALLOCATER();*//*INSANELY PERFECT*/
