DROP VIEW IF EXISTS USEDSTOCK;
CREATE
    VIEW USEDSTOCK 
    AS
(
SELECT FOOD.`ID`, FOODNAME, SUM(TYPEOFFOOD.QTY) - SUM(SUBORDERS.QTY) AS "STOCK REMAINING"
FROM TYPEOFFOOD
JOIN FOOD, SUBORDERS, FOODTOTYPEMAP, ORDERS WHERE TYPEID = TYPEOFFOOD.ID AND FOOD.ID = SUBORDERS.`FOODID` AND FOOD.`ID` = FOODTOTYPEMAP.FOODID AND ORDERSID = ORDERS.`ID` AND DATEDIFF(CURDATE(), TIMEANDDATE) = 0 AND ORDERSSTATUS = 1 GROUP BY FOOD.ID)

UNION

DROP VIEW IF EXISTS UNUSEDSTOCK;
CREATE VIEW UNUSEDSTOCK
AS(
SELECT FOOD.`ID`, FOODNAME, SUM(TYPEOFFOOD.QTY) AS "STOCK REMAINING"
FROM FOOD
JOIN TYPEOFFOOD, FOODTOTYPEMAP WHERE TYPEID = TYPEOFFOOD.ID AND FOOD.`ID` = FOODTOTYPEMAP.FOODID AND FOOD.ID NOT IN(SELECT FOOD.`ID` FROM TYPEOFFOOD JOIN FOOD, SUBORDERS, FOODTOTYPEMAP, ORDERS WHERE TYPEID = TYPEOFFOOD.ID AND FOOD.ID = SUBORDERS.FOODID AND FOOD.`ID` = FOODTOTYPEMAP.FOODID AND ORDERSID = ORDERS.`ID` AND DATEDIFF(CURDATE(), TIMEANDDATE) = 0 AND ORDERSSTATUS = 1 GROUP BY FOOD.ID) GROUP BY FOOD.ID) /*THE STOCKPILE REMAINS CODE*/)/*DOSEN'T  WORK WHATEVER I DO SEE TO IT FUTURE BRUH!!!!*/

SELECT * FROM USEDSTOCK
UNION
SELECT * FROM `UNUSEDSTOCK`;

EXTRACT(,